### ISSUE TITLE
remove "kinura_" from the beginning of file names

### ISSUE THREAD

**Issue by SamPassmore** [kinbank/kinura#8]
have the prefix "kinura_" in the raw file names causes a problem with the CLDF creation. 

It will be easiest if all file names have the format Name_glottocode.csv, moving forward.

**Comment by SamPassmore** [comment]
Hi Terhi, 

with the exception of Finnish in #3 we have removed all Varikin files from the Kinura dataset. Are you happy for me to remove the "kinura_" prefix now that we won't get them confused?

**Comment by tekahon** [comment]
I think once you have done the changes discussed in these Issues I think the kinura_ prefix can be removed.

**Comment by SamPassmore** [comment]
I have made this fix. All the kinura files should be on the kinbank website now.
