### ISSUE TITLE
Name of the expert in the source UR19

### ISSUE THREAD

**Issue by tekahon** [kinbank/kinura#9]
In the following reference the first name of the author should be Riho instead of Rohi. 

@misc{grunthalVeps1250TermsCollected2020,
    author = {Gr{\"u}nthal, Rohi},
    title = "Veps1250 Terms Collected from an Interview with Speaker",
    year = "2020",
    month = "January",
    keywords = "kinbank,UR19,veps1250"

**Comment by SamPassmore** [comment]
I can't find this reference anywhere in this file: 
kinbank/raw/sources.bib

Is this an issue with Varikin data?

**Comment by tekahon** [comment]
It is at least in kinbank/kinbank/raw/sources.bib https://github.com/kinbank/kinbank/blob/master/kinbank/raw/sources.bib#L2404C39-L2404C39

 in row 2404.

**Comment by tekahon** [comment]
And in varikin/kinbank/raw/sources.bib https://github.com/kinbank/varikin/blob/main/kinbank/raw/sources.bib it is in row 2348

**Comment by SamPassmore** [comment]
Ok. Thanks Terhi. I was looking in kinura, since the issue was linked to the kinura dataset.

**Comment by SamPassmore** [comment]
I fixed this in varikin
